### LabelEncoding
* sklearn.preprocessing.LabelEncoder


In [2]:
from sklearn.preprocessing import LabelEncoder

items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

le = LabelEncoder()
le.fit(['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서'])

le.transform(items)

array([0, 1, 4, 5, 3, 3, 2, 2])

In [4]:
results = le.transform(items)

In [6]:
results

array([0, 1, 4, 5, 3, 3, 2, 2])

In [8]:
le.inverse_transform([0,0,0,1,2])

array(['TV', 'TV', 'TV', '냉장고', '믹서'], dtype='<U4')

In [9]:
le.classes_

array(['TV', '냉장고', '믹서', '선풍기', '전자렌지', '컴퓨터'], dtype='<U4')

### sklearn.preprocessing.OneHotEncoder
* class sklearn.preprocessing.OneHotEncoder(*, categories='auto', drop=None, sparse='deprecated', sparse_output=True, dtype=<class 'numpy.float64'>, handle_unknown='error', min_frequency=None, max_categories=None, feature_name_combiner='concat')

In [18]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

encoder = OneHotEncoder()

item = np.array(items).reshape(-1,1)
encoder.fit(item)
data = encoder.transform(item).toarray()

In [23]:
data

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [28]:
import pandas as pd
df = pd.DataFrame(data,columns=['TV_ITEM','냉장고_ITEM','믹서ITEM','선풍기_ITEM','전자렌지_ITEM','컴퓨터_ITEM'], 
                            index=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서'])

In [29]:
df

TV_ITEM  냉장고_ITEM  믹서ITEM  선풍기_ITEM  전자렌지_ITEM  컴퓨터_ITEM
TV        1.0       0.0     0.0       0.0        0.0       0.0
냉장고       0.0       1.0     0.0       0.0        0.0       0.0
전자렌지      0.0       0.0     0.0       0.0        1.0       0.0
컴퓨터       0.0       0.0     0.0       0.0        0.0       1.0
선풍기       0.0       0.0     0.0       1.0        0.0       0.0
선풍기       0.0       0.0     0.0       1.0        0.0       0.0
믹서        0.0       0.0     1.0       0.0        0.0       0.0
믹서        0.0       0.0     1.0       0.0        0.0       0.0